-- Run in Supabase SQL Editor
-- Replace admin emails in the two policies below.

create table if not exists public.booking_requests (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null,
    email text not null,
    inquiry text not null,
    requested_date date null,
    venue text not null,
    offer_amount text not null,
    event_type text not null,
    other_artists text not null,
    promoter text not null,
    previous_bookings text not null,
    stage_time text not null,
    event_name text not null,
    message text not null
);

alter table public.booking_requests enable row level security;

create table if not exists public.managed_artists (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    artist_key text not null unique,
    name text not null,
    role text not null,
    category text not null,
    image_url text not null,
    instagram_url text null,
    twitter_url text null,
    spotify_url text null,
    youtube_url text null,
    subtitle text null,
    dob text null,
    genres text null,
    description text null,
    metrics text null
);

alter table public.managed_artists enable row level security;

create table if not exists public.managed_posters (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    image_url text not null,
    alt_text text not null default 'Booking highlight'
);

alter table public.managed_posters enable row level security;

create table if not exists public.managed_hero_slides (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    image_url text not null,
    alt_text text not null default 'Hero slide',
    title_line1 text null,
    title_line2 text null,
    tagline text null,
    primary_label text null default 'View Tour',
    primary_href text null default '#tours',
    secondary_label text null default 'Book Now',
    secondary_href text null default '#contact'
);

alter table public.managed_hero_slides enable row level security;

create table if not exists public.managed_news (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    image_url text not null,
    alt_text text not null default 'News image',
    date_label text not null default '2026',
    title text not null,
    excerpt text not null,
    link_label text not null default 'Read More',
    link_href text not null default '#contact'
);

alter table public.managed_news enable row level security;

create table if not exists public.managed_tour_sections (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    section_tag text not null default 'Upcoming',
    section_title text not null default 'Africa Tours 2026',
    is_active boolean not null default false
);

alter table public.managed_tour_sections enable row level security;

drop policy if exists "Public can create booking requests" on public.booking_requests;
create policy "Public can create booking requests"
on public.booking_requests
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read booking requests" on public.booking_requests;
create policy "Admins can read booking requests"
on public.booking_requests
for select
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete booking requests" on public.booking_requests;
create policy "Admins can delete booking requests"
on public.booking_requests
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Public can read managed artists" on public.managed_artists;
create policy "Public can read managed artists"
on public.managed_artists
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert managed artists" on public.managed_artists;
create policy "Admins can insert managed artists"
on public.managed_artists
for insert
to authenticated
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can update managed artists" on public.managed_artists;
create policy "Admins can update managed artists"
on public.managed_artists
for update
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
)
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete managed artists" on public.managed_artists;
create policy "Admins can delete managed artists"
on public.managed_artists
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Public can read managed posters" on public.managed_posters;
create policy "Public can read managed posters"
on public.managed_posters
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert managed posters" on public.managed_posters;
create policy "Admins can insert managed posters"
on public.managed_posters
for insert
to authenticated
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete managed posters" on public.managed_posters;
create policy "Admins can delete managed posters"
on public.managed_posters
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Public can read managed hero slides" on public.managed_hero_slides;
create policy "Public can read managed hero slides"
on public.managed_hero_slides
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert managed hero slides" on public.managed_hero_slides;
create policy "Admins can insert managed hero slides"
on public.managed_hero_slides
for insert
to authenticated
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can update managed hero slides" on public.managed_hero_slides;
create policy "Admins can update managed hero slides"
on public.managed_hero_slides
for update
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
)
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete managed hero slides" on public.managed_hero_slides;
create policy "Admins can delete managed hero slides"
on public.managed_hero_slides
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Public can read managed news" on public.managed_news;
create policy "Public can read managed news"
on public.managed_news
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert managed news" on public.managed_news;
create policy "Admins can insert managed news"
on public.managed_news
for insert
to authenticated
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can update managed news" on public.managed_news;
create policy "Admins can update managed news"
on public.managed_news
for update
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
)
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete managed news" on public.managed_news;
create policy "Admins can delete managed news"
on public.managed_news
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Public can read managed tour sections" on public.managed_tour_sections;
create policy "Public can read managed tour sections"
on public.managed_tour_sections
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert managed tour sections" on public.managed_tour_sections;
create policy "Admins can insert managed tour sections"
on public.managed_tour_sections
for insert
to authenticated
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can update managed tour sections" on public.managed_tour_sections;
create policy "Admins can update managed tour sections"
on public.managed_tour_sections
for update
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
)
with check (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);

drop policy if exists "Admins can delete managed tour sections" on public.managed_tour_sections;
create policy "Admins can delete managed tour sections"
on public.managed_tour_sections
for delete
to authenticated
using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in (
        'mcneilruel@gmail.com'
    )
);
